import {TCompany} from './t';

enum images {
  github = require('@src/assets/connects/github.png'),
  mail = require('@src/assets/connects/mail.png'),
  mobile = require('@src/assets/connects/mobile.png'),
  university = require('@src/assets/connects/university.png'),
  android = require('@src/assets/skills/android.png'),
  flutter = require('@src/assets/skills/flutter.png'),
  ios = require('@src/assets/skills/ios.png'),
  react = require('@src/assets/skills/react.png'),
  uni = require('@src/assets/skills/uni.png'),
  vue = require('@src/assets/skills/vue.png'),
  i = require('@src/assets/i.jpg'),
}

enum fonts {
  harmonyOS = 'HarmonyOS',
}

const companies = [
  {
    parent: '光汇石油集团',
    date: '2023年12月 ~ 2025年3月',
    children: [
      '云汇海运在线科技（深圳）有限公司',
      '深圳云油供油有限公司',
      '深圳快鹭科技有限公司',
    ],
    published: [
      {
        label: '海运在线App',
        markets: ['iOS: AppStore', 'android: Google Play'],
      },
      {
        label: '云供油小程序',
        markets: ['微信小程序'],
      },
      {
        label: '云供油SaaS运营平台',
      },
      {
        label: '云供油商城',
      },
      {
        label: '光汇集团官网',
        link: 'https://www.bwoil.com/',
        alive: true,
      },
      {
        label: '快鹭云SaaS运营平台',
        link: 'https://kl.quickegret.com/operation/#/',
        alive: true,
      },
      {
        label: '快鹭云SaaS管理后台',
        link: 'https://kl.quickegret.com/console/#/',
        alive: true,
      },
      {
        label: '快鹭云客户端 - PC&移动端',
        link: 'https://kl.quickegret.com/#/',
        alive: true,
      },
      {
        label: '快鹭云个人认证中心 - PC&移动端',
        link: 'https://auth.quickegret.com/#/login',
        alive: true,
      },
    ],
    projects: [
      '维护现有React Native项目，重构几十处选船、选港口的弹窗为公共组件；',
      '处理PayPal的升级，应对Google Pay强制升级Android 12的审核以及SDK升级的兼容；',
      '使用Uni-app对云供油的微信小程序进行现有问题的维护和新需求的开发，处理了uni-app的自带MapView在Android手机，尤其是鸿蒙手机上的体验，对于地图的视图范围、视图层级、Marker的懒加载有一定优化经验；',
      '使用element-ui对云供油SaaS运营平台和商城进行维护和新需求的开发；',
      '使用naive-ui对快鹭云的核心产品：SaaS运行平台、SaaS管理平台、SaaS客户端、个人认证中心，进行维护和新需求的开发；',
      '对移动端和PC端相同的业务逻辑进行Hooks封装，做到业务逻辑和视图的解耦。',
    ],
  },
  {
    parent: '云南白药集团上海健康产品有限公司',
    date: '2021年6月 ~ 2023年9月',
    children: [],
    published: [
      {
        label: '采之汲App',
        markets: ['iOS: AppStore', 'android: 华为、小米、OPPO、VIVO应用商店'],
      },
      {
        label: '采之汲微信小程序',
        markets: ['微信小程序'],
      },
      {
        label: '美创加App',
      },
    ],
    projects: [
      '参加2023年Google IO/Connect开发者大会Flutter专场；',
      '对React Native和Flutter进行技术调研和选型，基本框架使用Flutter，需要热更新和需要WebView交互的页面使用React Native；',
      '开源React Native瀑布流组件react-native-staggered-list，API无缝对接FlatList，支持列数自定义，自动计算高度，下拉刷新，上拉加载更多等；',
      '高度还原设计稿，进行android和iOS的屏幕的适配；',
      '搭建公共组件库，进行常用组件的封装；',
      '用Redux和Provider进行整个App数据流状态的管理以及必要时的数据缓存的工作；',
      '用axios和dio进行网络请求的二次封装，处理多个接口同步/异步访问的复杂业务的处理；',
      '用react-navigation对不同业务场景，进行路由的清栈、重定向等;',
      '对接微信支付和支付宝进行App内应用支付；',
      '处理地理位置授权，以及地理编码和逆地理编码，火星坐标等问题，用SQLite封装省/市/区四级联动位置选择器；',
      '编写原生iOS/android模块，处理必要时的React Native/Flutter的对于原生模块的需求；',
      '编写animation，满足指定场景下的交互体验；',
      '处理iOS上架过程中，隐私政策、用户协议、隐私权限话术、权限申请的时机等被拒的问题；',
      '处理android上架过程中，权限申请的时机，各个手机厂商的消息通知的消息通道的对接进行消息推送；',
      '用CodePush进行App指定功能页面的热更新；',
      '对新人的代码进行Code review，进行前端技术分享和新人培训；',
      '优化用户体验，对App进行性监测，以及收集线上用户行为埋点，进行用户行为的分析。',
    ],
  },
  {
    parent: '深圳市润丰数码技术有限公司',
    date: '2021年2月 ~ 2021年6月',
    children: [],
    published: [
      {label: 'Renpho Health', markets: ['iOS: AppStore']},
      {label: 'Renpho跨境电商后台管理系统', link: '--'},
    ],
    projects: [
      '独立负责React Native的开发，整合工厂硬件设备的SDK，封装视图；',
      '进行前端技术分享和技术培训；',
      '设备面板的搭建，按需加载JSBundle（App管理不同设备的JSBundle，定向进行设备更新）',
      '使用Ts&Hooks对现有的Js&class对Web项目进行重构。',
    ],
  },
  {
    parent: '深圳边度网络科技有限公司',
    date: '2020年6月 ~ 2021年2月',
    children: [],
    published: [{label: 'mPos', markets: ['iOS: AppStore']}],
    projects: [
      '编写原生android模块，集成讯飞语音SDK，进行TTS普通话、粤语和英语的语音播报；',
      '编写原生android模块，进行.zip的解压，.csv的处理；',
      '编写原生android模块，调用x86 POS机的硬件SDK进行热敏打印机的打印；',
      '编写原生android模块，进行八达通支付；',
      '调试模式的升级，可以在console输出android的网络请求日志，便于调试；',
      'React Native项目重构和升级，0.55版本升级到0.59版本，升级react-navigation 2.x到5.x版本，重构全局MobX+AsyncStorage为redux+redux-persist，Android support到AndroidX的升级，处理项目升级带来的其他的兼容性问题。',
    ],
  },
] as TCompany[];

const colors = [
  {label: '粉红', value: '#ffb3a7'},
  {label: '妃色', value: '#ed5736'},
  {label: '品红', value: '#f00056'},
  {label: '桃红', value: '#f47983'},
  {label: '海棠红', value: '#db5a6b'},
  {label: '石榴红', value: '#f20c00'},
  {label: '樱桃色', value: '#c93756'},
  {label: '银红', value: '#f05654'},
  {label: '大红', value: '#ff2121'},
  {label: '绛紫', value: '#8c4356'},
  {label: '绯红', value: '#c83c23'},
  {label: '胭脂', value: '#9d2933'},
  {label: '朱红', value: '#ff4c00'},
  {label: '丹', value: '#ff4e20'},
  {label: '彤', value: '#f35336'},
  {label: '茜色', value: '#cb3a56'},
  {label: '火红', value: '#ff2d51'},
  {label: '赫赤', value: '#c91f37'},
  {label: '嫣红', value: '#ef7a82'},
  {label: '洋红', value: '#ff0097'},
  {label: '炎', value: '#ff3300'},
  {label: '赤', value: '#c3272b'},
  {label: '绾', value: '#a98175'},
  {label: '枣红', value: '#c32136'},
  {label: '檀', value: '#b36d61'},
  {label: '殷红', value: '#be002f'},
  {label: '酡红', value: '#dc3023'},
  {label: '酡颜', value: '#f9906f'},
  {label: '鹅黄', value: '#fff143'},
  {label: '鸭黄', value: '#faff72'},
  {label: '樱草色', value: '#eaff56'},
  {label: '杏黄', value: '#ffa631'},
  {label: '杏红', value: '#ff8c31'},
  {label: '橘黄', value: '#ff8936'},
  {label: '橙黄', value: '#ffa400'},
  {label: '橘红', value: '#ff7500'},
  {label: '姜黄', value: '#ffc773'},
  {label: '缃色', value: '#f0c239'},
  {label: '橙色', value: '#fa8c35'},
  {label: '茶色', value: '#b35c44'},
  {label: '驼色', value: '#a88462'},
  {label: '昏黄', value: '#c89b40'},
  {label: '栗色', value: '#60281e'},
  {label: '棕色', value: '#b25d25'},
  {label: '棕绿', value: '#827100'},
  {label: '棕黑', value: '#7c4b00'},
  {label: '棕红', value: '#9b4400'},
  {label: '棕黄', value: '#ae7000'},
  {label: '赭', value: '#9c5333'},
  {label: '赭色', value: '#955539'},
  {label: '琥珀', value: '#ca6924'},
  {label: '褐色', value: '#6e511e'},
  {label: '枯黄', value: '#d3b17d'},
  {label: '黄栌', value: '#e29c45'},
  {label: '秋色', value: '#896c39'},
  {label: '秋香色', value: '#d9b611'},
  {label: '嫩绿', value: '#bddd22'},
  {label: '柳黄', value: '#c9dd22'},
  {label: '柳绿', value: '#afdd22'},
  {label: '竹青', value: '#789262'},
  {label: '葱黄', value: '#a3d900'},
  {label: '葱绿', value: '#9ed900'},
  {label: '葱青', value: '#0eb83a'},
  {label: '葱倩', value: '#0eb840'},
  {label: '青葱', value: '#0aa344'},
  {label: '油绿', value: '#00bc12'},
  {label: '绿沈', value: '#0c8918'},
  {label: '碧色', value: '#1bd1a5'},
  {label: '碧绿', value: '#2add9c'},
  {label: '青碧', value: '#48c0a3'},
  {label: '翡翠色', value: '#3de1ad'},
  {label: '草绿', value: '#40de5a'},
  {label: '青色', value: '#00e09e'},
  {label: '青翠', value: '#00e079'},
  {label: '青白', value: '#c0ebd7'},
  {label: '鸭卵青', value: '#e0eee8'},
  {label: '蟹壳青', value: '#bbcdc5'},
  {label: '鸦青', value: '#424c50'},
  {label: '绿色', value: '#00e500'},
  {label: '豆绿', value: '#9ed048'},
  {label: '豆青', value: '#96ce54'},
  {label: '石青', value: '#7bcfa6'},
  {label: '玉色', value: '#2edfa3'},
  {label: '缥', value: '#7fecad'},
  {label: '艾绿', value: '#a4e2c6'},
  {label: '松柏绿', value: '#21a675'},
  {label: '松花绿', value: '#057748'},
  {label: '松花色', value: '#bce672'},
  {label: '蓝', value: '#44cef6'},
  {label: '靛青', value: '#177cb0'},
  {label: '靛蓝', value: '#065279'},
  {label: '碧蓝', value: '#3eede7'},
  {label: '蔚蓝', value: '#70f3ff'},
  {label: '宝蓝', value: '#4b5cc4'},
  {label: '蓝灰色', value: '#a1afc9'},
  {label: '藏青', value: '#2e4e7e'},
  {label: '藏蓝', value: '#3b2e7e'},
  {label: '黛', value: '#4a4266'},
  {label: '黛绿', value: '#426666'},
  {label: '黛蓝', value: '#425066'},
  {label: '黛紫', value: '#574266'},
  {label: '紫色', value: '#8d4bbb'},
  {label: '紫酱', value: '#815463'},
  {label: '酱紫', value: '#815476'},
  {label: '紫檀', value: '#4c221b'},
  {label: '绀青绀紫', value: '#003371'},
  {label: '紫棠', value: '#56004f'},
  {label: '青莲', value: '#801dae'},
  {label: '群青', value: '#4c8dae'},
  {label: '雪青', value: '#b0a4e3'},
  {label: '丁香色', value: '#cca4e3'},
  {label: '藕色', value: '#edd1d8'},
  {label: '藕荷色', value: '#e4c6d0'},
  {label: '苍色', value: '#75878a'},
  {label: '苍翠', value: '#519a73'},
  {label: '苍黄', value: '#a29b7c'},
  {label: '苍青', value: '#7397ab'},
  {label: '苍黑', value: '#395260'},
  {label: '苍白', value: '#d1d9e0'},
  {label: '水色', value: '#88ada6'},
  {label: '水红', value: '#f3d3e7'},
  {label: '水绿', value: '#d4f2e7'},
  {label: '水蓝', value: '#d2f0f4'},
  {label: '淡青', value: '#d3e0f3'},
  {label: '湖蓝', value: '#30dff3'},
  {label: '湖绿', value: '#25f8cb'},
  {label: '精白', value: '#ffffff'},
  {label: '象牙白', value: '#fffbf0'},
  {label: '雪白', value: '#f2fdff'},
  {label: '月白', value: '#d6ecf0'},
  {label: '缟', value: '#f2ecde'},
  {label: '素', value: '#e0f0e9'},
  {label: '荼白', value: '#f3f9f1'},
  {label: '霜色', value: '#e9f1f6'},
  {label: '花白', value: '#c2ccd0'},
  {label: '鱼肚白', value: '#fcefe8'},
  {label: '莹白', value: '#e3f9fd'},
  {label: '灰色', value: '#808080'},
  {label: '牙色', value: '#eedeb0'},
  {label: '铅白', value: '#f0f0f4'},
  {label: '玄色', value: '#622a1d'},
  {label: '玄青', value: '#3d3b4f'},
  {label: '乌色', value: '#725e82'},
  {label: '乌黑', value: '#392f41'},
  {label: '漆黑', value: '#161823'},
  {label: '墨色', value: '#50616d'},
  {label: '墨灰', value: '#758a99'},
  {label: '黑色', value: '#000000'},
  {label: '缁色', value: '#493131'},
  {label: '煤黑', value: '#312520'},
  {label: '黧', value: '#5d513c'},
  {label: '黎', value: '#75664d'},
  {label: '黝', value: '#6b6882'},
  {label: '黝黑', value: '#665757'},
  {label: '黯', value: '#41555d'},
  {label: '赤金', value: '#f2be45'},
  {label: '金色', value: '#eacd76'},
  {label: '银白', value: '#e9e7ef'},
  {label: '老银', value: '#bacac6'},
  {label: '乌金', value: '#a78e44'},
  {label: '铜绿', value: '#549688'},
].sort(() => Math.random() - 0.5);

export {images, companies, fonts, colors};
